/**
 * Build — no dependencies, plain Node.
 *
 *   dist/index.html   the assembled single-file UI
 *   dist/worker.js    Cloudflare Worker, Service Worker format — paste into the dashboard editor
 *   dist/worker.mjs   Cloudflare Worker, ES module format      — `wrangler deploy`
 *
 * The Worker bundles are produced by concatenating the proxy core and the
 * Cloudflare host with their import/export syntax removed, so the pasted file
 * needs no build step on Cloudflare's side. The build checks its own output
 * (HTML round-trip, syntax, no leftover module syntax) before writing.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import vm from 'node:vm';
import { assembleHtml } from '../src/ui/assemble.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

/** Remove ES module syntax so sources can be concatenated into one classic script. */
export function stripModuleSyntax(src) {
  return src
    .replace(/^#!.*\n/, '')
    .replace(/^import\s[^;]+;[ \t]*\n?/gm, '')
    .replace(/^export\s+(async\s+function|function|const|let|var|class)\b/gm, '$1')
    .replace(/^export\s*\{[^}]*\};?[ \t]*\n?/gm, '');
}

/* src/core runs unchanged on the Worker, the Node server and (compliance) in tests,
   so it may not reach for any one platform. Cloudflare-only names are the ones a
   Worker gets for free and Node does not. */
const PLATFORM_ONLY = [
  [/\bfrom\s*['"]node:|\bimport\s*\(\s*['"]node:|\brequire\s*\(/, 'imports a node: module'],
  [/\b(HTMLRewriter|WebSocketPair|caches\.default|__STATIC_CONTENT)\b/, 'uses a Cloudflare-only API'],
];

function jsFilesUnder(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? jsFilesUnder(join(dir, e.name)) : (e.name.endsWith('.js') ? [join(dir, e.name)] : []));
}

/** Every platform-specific reach in a platform-free tree, as "file: reason" */
export function platformViolations(dir) {
  const out = [];
  for (const file of jsFilesUnder(dir)) {
    const src = readFileSync(file, 'utf8');
    for (const [pattern, reason] of PLATFORM_ONLY) if (pattern.test(src)) out.push(relative(ROOT, file) + ': ' + reason);
  }
  return out;
}

/** Core sources concatenated into the Worker, dependencies first */
const CORE_FILES = [
  'src/core/proxy.js', 'src/core/oauth-client.js', 'src/core/security-headers.js',
  'src/core/compliance/rules/version.js', 'src/core/compliance/catalogue.js', 'src/core/compliance/engine.js',
];

/** Embed arbitrary text as a JS template literal. */
export function toTemplateLiteral(text) {
  return '`' + text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

function banner(format) {
  const deploy = format === 'sw'
    ? [
        ' * DEPLOY (dashboard, no CLI):',
        ' *   1. dash.cloudflare.com → Workers & Pages → Create → Workers → "Start with Hello World!"',
        ' *   2. Deploy, then "Edit code" → select ALL existing code → delete → paste this file → Deploy',
        ' *   3. Open https://<name>.<your-subdomain>.workers.dev',
      ]
    : [
        ' * DEPLOY: `npx wrangler deploy` (uses wrangler.toml → main = "dist/worker.mjs")',
      ];
  return [
    '/**',
    ` * MCP Tester ${pkg.version} — Cloudflare Worker (${format === 'sw' ? 'Service Worker' : 'ES module'} format)`,
    ' * GENERATED by scripts/build.mjs — do not edit; change src/ and rebuild.',
    ' *',
    ...deploy,
    ' *',
    ' * OPTIONAL: set ALLOWED_ORIGINS (Settings → Variables) to restrict which hosts this',
    ' * Worker will proxy to, e.g. "developer.hsbc.com". Include the authorization server',
    ' * hosts too if you sign in. This Worker is public: put Cloudflare Access in front of',
    ' * it before using it with credentials, with a bypass for /oauth/client-metadata.json',
    ' * so authorization servers can fetch the client metadata document.',
    ' */',
    '',
  ].join('\n');
}

export function build({ write = true, coreDir = join(ROOT, 'src', 'core') } = {}) {
  const platform = platformViolations(coreDir);
  if (platform.length) throw new Error('src/core must stay platform-free:\n  ' + platform.join('\n  '));
  const html = assembleHtml();
  const core = CORE_FILES
    .map((f) => stripModuleSyntax(readFileSync(join(ROOT, f), 'utf8'))).join('\n');
  const host = stripModuleSyntax(readFileSync(join(ROOT, 'src/hosts/cloudflare.js'), 'utf8'));
  const htmlConst = 'const HTML = ' + toTemplateLiteral(html) + ';\n\n';

  const sw = banner('sw') + htmlConst + core + '\n' + host + '\n' +
    'addEventListener("fetch", function (event) {\n' +
    '  event.respondWith(handleRequest(event.request, typeof ALLOWED_ORIGINS !== "undefined" ? ALLOWED_ORIGINS : ""));\n' +
    '});\n';

  const mod = banner('module') + htmlConst + core + '\n' + host + '\n' +
    'export default {\n' +
    '  fetch(request, env) {\n' +
    '    return handleRequest(request, (env && env.ALLOWED_ORIGINS) || "");\n' +
    '  },\n' +
    '};\n';

  // ── self-checks ──
  const roundTrip = vm.runInNewContext(toTemplateLiteral(html));
  if (roundTrip !== html) throw new Error('HTML template literal does not round-trip');
  new vm.Script(sw, { filename: 'worker.js' });                    // throws on syntax error
  if (/^\s*(import|export)\s/m.test(sw)) throw new Error('module syntax left in worker.js');
  if ((mod.match(/^export\s/gm) || []).length !== 1) throw new Error('worker.mjs must have exactly one export');

  if (write) {
    mkdirSync(DIST, { recursive: true });
    writeFileSync(join(DIST, 'index.html'), html);
    writeFileSync(join(DIST, 'worker.js'), sw);
    writeFileSync(join(DIST, 'worker.mjs'), mod);
  }
  return { html, sw, mod };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { html, sw, mod } = build();
  const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';
  console.log(`MCP Tester ${pkg.version} built:`);
  console.log(`  dist/index.html  ${kb(html)}`);
  console.log(`  dist/worker.js   ${kb(sw)}   ← paste into the Cloudflare dashboard`);
  console.log(`  dist/worker.mjs  ${kb(mod)}   ← wrangler deploy`);
}
